<div class="two-column-layout column-layout clearfix">
	<div class="column-1 column"><?php include(dirname(__FILE__).'/_menu.phtml'); ?></div>
	<div class="column-2 column">
		<?php if($content): ?>
		<?php echo $content; ?>
		<div id="disqus_thread"></div>
		<?php else: ?>
		<h3>Template 1</h3>
		
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam congue, lectus et pharetra consequat, 
		lectus mauris tincidunt urna, a cursus arcu sapien quis eros. Nulla turpis diam, vehicula non vulputate 
		in, ornare non felis. Morbi pulvinar, ipsum in rhoncus pretium, nunc urna feugiat arcu, quis blandit est 
		nunc ac sapien. In hac habitasse platea dictumst. Maecenas venenatis ipsum quam. Curabitur gravida 
		blandit malesuada. Quisque eget velit lectus. Praesent quis sapien vel dolor commodo mattis.</p>
		
		<h4>Section 1</h4>
		
		<p>Phasellus laoreet libero est. Aliquam tincidunt pellentesque lectus eget dictum. Nullam ultrices 
		adipiscing urna nec ullamcorper. Proin consequat mollis turpis sed feugiat. In bibendum est eu risus 
		elementum pharetra. Morbi ultricies ultricies nisi sit amet pretium. Maecenas cursus augue in ligula 
		iaculis tempor. In hac habitasse platea dictumst. Praesent nec ante et turpis molestie bibendum. 
		Vestibulum feugiat felis molestie lacus cursus sodales.</p>
		
		<blockquote class="error clearfix"><span class="icon"></span>Proin consequat mollis turpis sed feugiat. In bibendum est eu risus elementum pharetra.</blockquote>
		
		<ul>
			<li>Unordered Item 1</li>
			<li>Unordered Item 2</li>
			<li>Unordered Item 3</li>
		</ul>
		
		<p>Nam nec tempor sem. Nunc tempus lorem hendrerit felis laoreet eget laoreet magna scelerisque. 
		Maecenas posuere, justo id fringilla lacinia, odio ipsum sagittis mi, ac luctus ligula lectus quis 
		eros. Quisque vulputate metus a mauris pulvinar facilisis. Integer quis tellus ligula. Vestibulum 
		posuere mollis lectus, at sollicitudin ligula facilisis non. Nunc gravida pulvinar ante et bibendum. 
		Aenean et nisi justo. Mauris id felis diam. Phasellus pulvinar aliquam est, ut ultrices tellus aliquet 
		ullamcorper. Maecenas quam lorem, sodales ut congue a, malesuada id nibh. Pellentesque nec elit eros, 
		et convallis urna. Cras sit amet neque id velit placerat luctus.</p>
		
		<ol>
			<li>Ordered Item 1</li>
			<li>Ordered Item 2</li>
			<li>Ordered Item 3</li>
		</ol>
		
		<blockquote class="tip clearfix"><span class="icon"></span>Proin consequat mollis turpis sed feugiat. In bibendum est eu risus elementum pharetra.</blockquote>
		
		<p>Nulla facilisi. Nullam vulputate tortor bibendum justo rhoncus accumsan. Nunc pellentesque nibh 
		vel elit pellentesque sit amet consectetur nisl elementum. Fusce egestas scelerisque sem, ultricies 
		porta arcu suscipit sagittis. Nulla facilisi. Maecenas ac lectus non est tincidunt posuere. 
		Nunc vehicula congue magna, pharetra porta elit mattis vulputate. Aenean interdum arcu non dui 
		ultricies semper. Phasellus pellentesque semper sagittis. Nunc ante dolor, imperdiet a vulputate 
		non, ultricies et arcu. Fusce ac ligula vel arcu convallis euismod quis nec massa.</p>
		
		<sub>Figure 1</sub>
		<div class="example"><pre class="brush: php;">Some Code</pre></div>
		
		
		<blockquote class="warning clearfix"><span class="icon"></span>Quisque vulputate metus a mauris pulvinar facilisis.</blockquote>
		
		<p>Mauris nisi odio, pellentesque sit amet dapibus at, scelerisque ac metus. Donec at nunc id sapien 
		vestibulum consequat. Pellentesque vitae mauris vitae nunc pellentesque gravida at sit amet eros. 
		Mauris quis enim leo. Suspendisse consectetur orci quis leo tristique mattis. Sed rutrum ligula quis 
		quam aliquam faucibus. Suspendisse potenti. Praesent gravida, tellus vel adipiscing mollis, metus risus 
		porta nunc, fermentum malesuada leo urna at justo. Etiam a erat ut neque tempor congue nec vel diam. 
		Pellentesque dapibus, nunc vel porttitor rhoncus, risus massa faucibus nulla, vel convallis erat nunc 
		eu lectus. Aenean interdum sagittis elit, in feugiat quam cursus nec. Fusce ac est at risus rhoncus 
		vestibulum in mollis sapien. Curabitur nec orci eu magna commodo aliquet vitae nec orci. Morbi ipsum 
		felis, euismod non luctus ut, fringilla vulputate massa. Praesent vitae orci ante, sed ultrices augue. 
		Quisque sagittis magna non elit tempus mattis.</p>
		
		<blockquote class="note">
			<h5>Author Note</h5>
			<span>Quisque vulputate metus a mauris pulvinar facilisis.</span>
		</blockquote>
		
		<a class="prev">&laquo; Previous</a>
		<a class="next">Next &raquo;</a>
		
		<?php endif; ?>
	</div>
</div>

<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'edenphplibrary'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>