<div class="two-column-layout column-layout clearfix">
	<div class="column-1 column">
		<h3>Eden v0.2.<?php echo $version; ?> Downloads</h3>
		<p>We are making possible to download <strong>Eden</strong> easier. If you just want to try it first. We 
		recommend you download the 1 file version on the right. The 1 file comes with everything except for blocks.
		Blocks are pieces of reusable output code usually in HTML. If you want to try out everything including blocks,
		proceed to click the button below.</p>
        <form method="post">	
			<input name="download" type="image" src="/assets/images/download.png" value="Download 1 File" />
			<a href="http://svn.openovate.com/edenv2/trunk/library/" target="_blank">SVN checkout</a>
        </form><br /><br />
		<h3>Sample Projects</h3>
		<p>Although Eden doesn't specifically include how to handle page requests. We still use her to build all of 
		our websites here at Openovate Labs. Our sandbox includes an example front end application that's currently
		used to build this site.</p>
		<a href="#">Get the sandbox</a>
	</div>
    <div class="column-2 column">
		<div class="box">
        <h4>Get it in one file!</h4>
        <form method="post">
			<span>Select Available Packages:</span><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="utilities" /> Utilities</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="cache" /> Cache, MemCache, APC</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="mail" /> POP3, SMTP, IMAP</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="mysql" /> MySQL</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="postgre" /> PostGres</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="sqlite" /> Sqlite</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="amazon" /> Amazon</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="eventbrite" /> Eventbrite</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="facebook" /> Facebook</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="twitter" /> Twitter</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="tumblr" /> Tumblr</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="getsatisfaction" /> Get Satisfaction</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="jabber" /> Jabber</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="paypal" /> PayPal</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="authorizenet" /> Authorize.net</label><br />
			<label><input type="checkbox" class="checkbox" name="package[]" value="xend" /> Xend</label><br /><br />
			<input type="image" src="/assets/images/download.png" value="Download 1 File" />
        </form>
		</div>
    </div>
</div>