<a class="prev" href="/docs/start">&laquo; I. Getting Started</a>
<a class="next" href="/docs/library/features">1. Features &raquo;</a>
<h3>II. The Library</h3>

<p><strong>Eden</strong> is a PHP Library maintained by <a href="http://openovate.com/" target="_blank">Openovate Labs</a>. We use <strong>Eden</strong> as a foundation for all of our internal product development, which in turn keeps her code base updated, evolving and constantly expanding. <strong>Eden</strong> is classified as a library <em>(versus a CMS or Framework)</em> because her only ambition is to make functionality available rather than make rules for how a website is created. This makes learning <strong>Eden</strong> easier because you only need to learn the classes you plan to use.</p>
		
		<blockquote class="warning clearfix">
			<span class="icon"></span>
			Eden is not specifically designed for building websites by design. Technically, you can use Eden as a compliment anywhere you were planning to use PHP in your project.
		</blockquote>
		
		<p>The library is separated into different sections covering databases, caching, file system, persistent data, etc. which is common in most frameworks, but <strong>Eden</strong> also covers web services, payment gateways, shipping and cloud technologies out of the box.</p>
		
		<h5>What's Out of the Box:</h5>
		<ul class="three-column clearfix">
			<li><a href="/docs/library/mysql">MySQL</a></li>
			<li><a href="/docs/library/sqlite">SQLite</a></li>
			<li><a href="/docs/library/posgres">PosgreSQL</a></li>
			<li><a href="/docs/library/mongo">MongoDB</a> (IN DEV)</li>
			<li><a href="/docs/library/memcache">Memcache</a></li>
			<li><a href="/docs/library/apc">APC</a></li>
			<li><a href="/docs/library/mailing/imap">IMAP</a></li>
			<li><a href="/docs/library/mailing/smtp">SMTP</a></li>
			<li><a href="/docs/library/mailing/pop3">POP3</a></li>
			<li><a href="/docs/library/google/calendar">Google Calendar</a> (IN DEV)</li>
			<li><a href="/docs/library/google/docs">Google Docs</a> (IN DEV)</li>
			<li><a href="/docs/library/google/gmail">Gmail</a> (IN DEV)</li>
			<li><a href="/docs/library/google/contacts">Google Contacts</a> (IN DEV)</li>
			<li><a href="/docs/library/google/maps">Google Maps</a> (IN DEV)</li>
			<li><a href="/docs/library/google/plus">Google+</a> (IN DEV)</li>
			<li><a href="/docs/library/google/shortner">Google Shortner</a></li>
			<li><a href="/docs/library/facebook">Facebook</a></li>
			<li><a href="/docs/library/twitter">Twitter</a></li>
			<li><a href="/docs/library/tumbler">Tumbler</a></li>
			<li><a href="/docs/library/getsatisfaction">Get Satisfaction</a></li>
			<li><a href="/docs/library/eventbrite">Eventbrite</a></li>
			<li><a href="/docs/library/webcharge">Web Charge</a> (IN DEV)</li>
			<li><a href="/docs/library/paypal">Paypal</a></li>
			<li><a href="/docs/library/authorizenet">Authorize.net</a></li>
			<li><a href="/docs/library/lbc">LBC</a> (IN DEV)</li>
			<li><a href="/docs/library/fedex">FedEx</a> (IN DEV)</li>
			<li><a href="/docs/library/ups">UPS</a> (IN DEV)</li>
			<li><a href="/docs/library/dhl">DHL</a> (IN DEV)</li>
			<li><a href="/docs/library/xend">Xend</a></li>
			<li><a href="/docs/library/amazon">Amazon EC2 &amp; S3</a> (ADDING EC2)</li>
			<li><a href="/docs/library/jabber">Jabber</a></li>
		</ul>
		
		<p>Although <strong>Eden</strong> support the above services, it's not enough to say it works. We focus on <em>end developer</em> usage; getting results or performing actions with less code. <sub>Figure 1</sub>, for example, shows how easy it is to get your <strong>Facebook</strong> friends.</p>
		
		<sub>Figure 1. Get a Pure Array of Facebook Friends</sub>
		<div class="example"><pre class="brush: php;">
		$friends = eden('facebook')->graph('[YOUR ACCESS TOKEN]')->getFriends();
		</pre></div>
		
		<p>On a core level, <strong>Eden</strong> is designed to be a game changer, from writing code to new concepts, more things are possible. To learn more about the features of <strong>Eden</strong> in detail, head over to <a href="/docs/library/features">1. Features</a></p> 
		
<a class="prev" href="/docs/start">&laquo; I. Getting Started</a>
<a class="next" href="/docs/library/features">1. Features &raquo;</a>
